# Generated by Django 3.0.3 on 2020-02-24 10:43

import break_to_take.core.managers.user_manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', break_to_take.core.managers.user_manager.UserManager()),
            ],
        ),
    ]
